### PR TITLE
fix: now svg can be uploaded

### LINKED ISSUE #1628: Uploading SVG - 'Context' object has no attribute 'request'
Hi folks, I caught some errors while uploading SVG files to the thumbor. 
On the 6.x versions of thumbor uploading SVG works fine. But I've tried Minimalcompact's latest versions, 7.6, and 7.5, and also tried a fresh install from pip - all the same error:

```
2023-12-02 11:38:22 thumbor:ERROR ERROR: Traceback (most recent call last):
  File .../tmp/lib/python3.11/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File ".../tmp/lib/python3.11/site-packages/thumbor/handlers/upload.py", line 40, in post
    if self.validate(body):
       ^^^^^^^^^^^^^^^^^^^
  File ".../tmp/lib/python3.11/site-packages/thumbor/handlers/__init__.py", line 1044, in validate
    engine.load(body, None)
  File ".../tmp/lib/python3.11/site-packages/thumbor/engines/__init__.py", line 199, in load
    buffer = self.convert_svg_to_png(buffer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../tmp/lib/python3.11/site-packages/thumbor/engines/__init__.py", line 177, in convert_svg_to_png
    output_width=self.context.request.width,
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Context' object has no attribute 'request'

2023-12-02 11:38:22 tornado.access:ERROR 500 POST /image (127.0.0.1) 2.38ms
```

This happens with all SVG files I tried, and the same files work fine on the thumbor version  6.7.5
Can you point me please - what's going wrong and how to fix it?

### Thumbor request URL

POST /image
with the SVG content as a body

### Operating system
ArchLinux, minimal-compact docker image

### PR DESCRIPTION
**Pull request by RaphaelVRossi**
Closes #1628

### CODE REVIEW

**Review by scorphus — COMMENTED** [review]
@RaphaelVRossi, what would you think about giving this commit a more descriptive message? What does this commit change? The fact that "now svg can be uploaded" is an outcome of the changes.

Also, are SVG and GIF the only formats affected?

Thanks!
