### ISSUE TITLE
CV_P2GRAY on 5.2.1: Error in log can't understand why

### ISSUE THREAD

**Issue by smagnaschi** [thumbor/thumbor#647]
```
2016-02-01 09:18:22 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 166, in do_smart_detection
    detectors[0](self.context, index=0, detectors=detectors).detect(self.after_smart_detect)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/detectors/face_detector/__init__.py", line 28, in detect
    features = self.get_features()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/detectors/local_detector.py", line 47, in get_features
    convert_mode = getattr(cv, 'CV_%s2GRAY' % mode)
AttributeError: 'module' object has no attribute 'CV_P2GRAY'

```

**Comment by smagnaschi** [comment]
It started after an upgrade from 5.0.6 to 5.2.1.

Server goes in gateway timout trying to resize this image:
http://www.rockol.it/assets/img/2015-design/placeholder-rockol.20150611v01.png

Version 5.0.6 has no problem with it.

**Comment by guilhermef** [comment]
Which version of opencv are you using ?
Em 01/02/2016 09:09, "smagnaschi" <notifications@github.com> escreveu:

**Comment by guilhermef** [comment]
Can you try the [6.0.0b1](https://pypi.python.org/pypi/thumbor/6.0.0b1) ?

**Comment by smagnaschi** [comment]
By running
`pkg-config --modversion opencv`

I get **2.4.8**

What's the best way to upgrade to 6.0.0b1? 
I usually update with

`pip install -U thumbor`

**Comment by guilhermef** [comment]
You can run pip install -U Thumbor==6.0.0b1
Em 01/02/2016 13:07, "smagnaschi" <notifications@github.com> escreveu:

**Comment by smagnaschi** [comment]
I can confirm that with 6.0.0b1 the image is handled correctly. It still goes on timeout if I rollback to 5.2.1.

**Comment by guilhermef** [comment]
@smagnaschi We've fixed the way that opencv handle images on 6.0.0b1.
On 5.2.1 OpenCv was handling the image conversion, now the engines does it,
so I recommend that you use the 6.0.0b1.
Is that ok ?

**Comment by smagnaschi** [comment]
Absolutely, thanks for all your work!

**Comment by guilhermef** [comment]
@smagnaschi can I close this issue ?

**Comment by smagnaschi** [comment]
Sure, go ahead, thanks.

**Comment by hus787** [comment]
@guilhermef would the fix take care of

```
2016-02-08 13:46:31 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/src/app/src/thumbor/thumbor/transformer.py", line 166, in do_smart_detection
    detectors[0](self.context, index=0, detectors=detectors).detect(self.after_smart_detect)
  File "/usr/src/app/src/thumbor/thumbor/detectors/feature_detector/__init__.py", line 31, in detect
    convert_mode = getattr(cv, 'CV_%s2GRAY' % image_mode)
AttributeError: 'module' object has no attribute 'CV_P2GRAY'
```
?

because this one occuring in `feature_detector` and the one reported here is in `local_detector`

**Comment by guilhermef** [comment]
@hus787 it should fix this error too.
