### ISSUE TITLE
Can no longer access XMP tags from WebP images via `engine.metadata`

### ISSUE THREAD

**Issue by dkbarn** [thumbor/thumbor#1629]
### Thumbor request URL
http://localhost/unsafe/60x60/smart/filters:format(jpeg)/1663499.webp

### Expected behaviour
XMP metadata is accessible via `engine.metadata`

### Actual behaviour
`engine.metadata` is returning None

### Operating system
Ubuntu 22.04

### Your thumbor.conf
```
THUMBOR_LOG_FORMAT = '%(asctime)s %(levelname)8s: [%(process)d][%(threadName)s] %(name)s: %(message)s'
LOADER = 'dbarn.thumbor.loader'
STORAGE = 'thumbor.storages.no_storage'
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
STORAGE_EXPIRATION_SECONDS = 2592000
FILE_STORAGE_ROOT_PATH = '/share/dev/data/dbarn/thumbor_cache/storage'
DETECTORS = [
    'dbarn.thumbor.face_detector',
    'thumbor.detectors.feature_detector',
]
FILTERS = [
    'dbarn.thumbor.highlight_faces',
    'thumbor.filters.format',
]
RESULT_STORAGE_EXPIRATION_SECONDS = 432000
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/share/dev/data/dbarn/thumbor_cache/result_storage'
RESULT_STORAGE_STORES_UNSAFE = True
```

I recently upgraded from Thumbor 7.0.12 to 7.7.2, and in the process the loading of XMP tags from WebP images has broken. I suspect this may have been caused by the replacement of pyexiv2 with piexif. I have a custom detector called `face_detector` which is doing the following:

```python
class Detector(BaseDetector):

    async def detect(self):
        # extract face bounding boxes from Xmp metadata embedded in image
        metadata = self.context.request.engine.metadata

        unit_key = "Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:unit"
        if unit_key in metadata.xmp_keys:
            assert metadata[unit_key].value == "pixel"
            width = int(metadata["Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:w"].value)
            height = int(metadata["Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:h"].value)
            ...
```

After upgrading to 7.7.2, all of a sudden I am getting the error:
```
  File "/opt/venv/lib/python3.10/site-packages/dbarn/thumbor/face_detector.py", line 14, in detect
    if unit_key in metadata.xmp_keys:
AttributeError: 'NoneType' object has no attribute 'xmp_keys'
```

The way this metadata is getting written into the WebP files has not changed. For reference, here is what that looks like:
```python
import pyexiv2
metadata = pyexiv2.ImageMetadata.from_buffer(media_data)
metadata.read()

# Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Name
def set_xmp_tag(key, value):
    metadata[key] = pyexiv2.XmpTag(key, value)

set_xmp_tag("Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:unit", "pixel")
set_xmp_tag("Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:w", width)
set_xmp_tag("Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:h", height)

# I don't really understand why this is important, but none of the indexed
# RegionLists get written out without it. Copied from example at end of:
# https://python3-exiv2.readthedocs.io/en/latest/tutorial.html#reading-and-writing-xmp-tags
set_xmp_tag("Xmp.mwg-rs.Regions/mwg-rs:RegionList", [""])

for i, face in enumerate(faces):
    # Xmp arrays begin at index 1, not 0
    index = i + 1

    # x and y are the center of the face, relative to the image dimensions
    # where top-left = (0,0)
    center_x = (face.left + face.right) / 2
    center_y = (face.top + face.bottom) / 2
    rel_x = center_x / width
    rel_y = center_y / height
    rel_w = (face.right - face.left) / width
    rel_h = (face.bottom - face.top) / height

    set_xmp_tag(f"Xmp.mwg-rs.Regions/mwg-rs:RegionList[{index}]/mwg-rs:Type", "Face")
    set_xmp_tag(f"Xmp.mwg-rs.Regions/mwg-rs:RegionList[{index}]/mwg-rs:Name", face.id)
    set_xmp_tag(f"Xmp.mwg-rs.Regions/mwg-rs:RegionList[{index}]/mwg-rs:Area/stArea:unit", "normalized")
    set_xmp_tag(f"Xmp.mwg-rs.Regions/mwg-rs:RegionList[{index}]/mwg-rs:Area/stArea:w", rel_w)
    set_xmp_tag(f"Xmp.mwg-rs.Regions/mwg-rs:RegionList[{index}]/mwg-rs:Area/stArea:h", rel_h)
    set_xmp_tag(f"Xmp.mwg-rs.Regions/mwg-rs:RegionList[{index}]/mwg-rs:Area/stArea:x", rel_x)
    set_xmp_tag(f"Xmp.mwg-rs.Regions/mwg-rs:RegionList[{index}]/mwg-rs:Area/stArea:y", rel_y)

metadata.write()
```

Is this an expected loss of functionality when Thumbor switched from pyexiv2 to piexif?
